<?php
include("./includes/head.inc");
include("./includes/nav.inc");
include("./includes/header.inc");
include("./includes/basic-content.inc");
include("./includes/churches.inc");
include("./includes/events.inc");
include("./includes/contact.inc");
include("./includes/foot.inc");